# Generated by Django 5.2.10 on 2026-01-12 14:53

import django.db.models.deletion
import master.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='warehouse',
            field=models.ForeignKey(default=master.models.get_default_warehouse_id, on_delete=django.db.models.deletion.PROTECT, related_name='stock_ins', to='master.warehouse'),
        ),
        migrations.AddField(
            model_name='stockinitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_in_items', to='master.product'),
        ),
        migrations.AddField(
            model_name='stockinitem',
            name='stock_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockin'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='master.product'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(default=master.models.get_default_warehouse_id, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='master.warehouse'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='warehouse',
            field=models.ForeignKey(default=master.models.get_default_warehouse_id, on_delete=django.db.models.deletion.PROTECT, related_name='stock_outs', to='master.warehouse'),
        ),
        migrations.AddField(
            model_name='stockoutitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_out_items', to='master.product'),
        ),
        migrations.AddField(
            model_name='stockoutitem',
            name='stock_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockout'),
        ),
        migrations.AlterUniqueTogether(
            name='stockinitem',
            unique_together={('stock_in', 'product')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'created_at'], name='inventory_s_product_92fcf9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='inventory_s_movemen_605463_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(fields=('movement_type', 'source_item_id'), name='uniq_stockmovement_source_item_per_type'),
        ),
        migrations.AlterUniqueTogether(
            name='stockoutitem',
            unique_together={('stock_out', 'product')},
        ),
    ]
