# Generated by Django 5.2.10 on 2026-01-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Daftar Produk',
                'verbose_name_plural': 'Daftar Produk',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('master.product',),
        ),
        migrations.CreateModel(
            name='ReportStockCardMovement',
            fields=[
            ],
            options={
                'verbose_name': 'Stock Card',
                'verbose_name_plural': 'Stock Card',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.stockmovement',),
        ),
    ]
